name: 'Infra Deployment East US'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Which environment to deploy to"
        required: true
        default: "dev"
        type: choice
        options:
          - Dev
          - QA
          - Prod
          
permissions:
  id-token: write  # Add this line to enable OIDC token request
  contents: read   # Required for checking out the repository

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment:  ${{ inputs.environment}}
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      #AZURE_STORAGE_ACCESS_KEY: ${{ secrets.AZURE_STORAGE_ACCESS_KEY }}
     # BACKEND_RESOURCE_GROUP_NAME: ${{ vars.BACKEND_RESOURCE_GROUP_NAME }}
      #BACKEND_STORAGE_ACCOUNT_NAME: ${{ vars.BACKEND_STORAGE_ACCOUNT_NAME }}
      #BACKEND_CONTAINER_NAME: ${{ vars.BACKEND_CONTAINER_NAME }}
      #BACKEND_KEY: ${{ github.event.inputs.environment }}
      # Terraform backend configuration values
      TF_VAR_storage_account_name: ${{ vars.BACKEND_STORAGE_ACCOUNT_NAME }}
      TF_VAR_container_name: ${{ vars.BACKEND_CONTAINER_NAME }}
      TF_VAR_key: ${{ github.event.inputs.environment }}
      TF_VAR_resource_group_name: ${{ vars.BACKEND_RESOURCE_GROUP_NAME }}
      TF_VAR_access_key: ${{ secrets.AZURE_STORAGE_ACCESS_KEY }}
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        # Change the working directory based on our environment
        working-directory: ${{ github.workspace }}/Infra/east_us

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.8.5

    #- name: Make script executable
    #  run: chmod +x ./generate_backend.sh

    #- name: Generate backend.tf
     # run:  ./generate_backend.sh

    #- name: Verify backend.tf
     # run: cat backend.tf  

    - name: Checkov GitHub Action
      uses: bridgecrewio/checkov-action@v12
      with:
        directory: ${{ github.workspace }}/Infra/east_us
        # This will add both a CLI output to the console and create a results.sarif file
        # output_format: cli,sarif
        # output_file_path: console,results.sarif
        soft_fail: true  # Set to true if you want to allow failures

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init 
      run: terraform init -reconfigure \
        -backend-config="storage_account_name=${{ env.TF_VAR_storage_account_name }}" \
        -backend-config="container_name=${{ env.TF_VAR_container_name }}" \
        -backend-config="key=${{ env.TF_VAR_key }}" \
        -backend-config="resource_group_name=${{ env.TF_VAR_resource_group_name }}" \
        -backend-config="access_key=${{ env.TF_VAR_access_key }}"

    # Generates an execution plan for Terraform
    - name: Terraform Plan 
      run: terraform plan -var-file=env/${{ github.event.inputs.environment }}.tfvars
     
    #- name: Create Approval Issue
     # uses: trstringer/manual-approval@v1
      #with:
       #       secret: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        #      approvers: adarshashokk
         #     minimum-approvals: 1
          #    issue-title: "Deploying ${{ github.event.inputs.environment }} to ${{ github.event.inputs.environment }}"
           #   issue-body: |
            #    Review the Terraform plan, then approve or deny the deployment of v1.0.0 to ${{ github.event.inputs.environment }}.
             #   - [ ] Approve
              #  - [ ] Deny
       
    - name: Terraform Apply
      run: terraform apply -var-file=env/${{ github.event.inputs.environment }}.tfvars -auto-approve
