name: Terraform Plan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:   # Allows manual triggering from GitHub UI

jobs:
  terraform:
    name: 'Terraform'
    runs-on: 'ubuntu-latest'
    environment:  "Dev"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -input=false
